export type Lang = 'ru'|'en'|'de';
export const copy = {
ru: {
 tagline:'Твои идеи. Сила AI.', newChat:'Новый чат', workspace:'Пространство', chat:'Чат с AI', image:'Изображения', video:'Видео', voice:'Озвучка', face:'Face Swap', live:'Разговор с AI', bots:'Мои боты', integrations:'Подключения', library:'Библиотека', billing:'Тарифы и кредиты', settings:'Настройки', tools:'ИНСТРУМЕНТЫ', manage:'УПРАВЛЕНИЕ',
 welcome:'Пространство для твоих идей', headline:'Что создадим', today:'сегодня?', intro:'От первого «а что, если» — до чего-то удивительного.', placeholder:'Опиши свою идею…', hint:'Enter — отправить · Shift + Enter — новая строка', aiNote:'AI может ошибаться. Проверяй важную информацию.', demo:'Предпросмотр', demoNote:'Демо интерфейса · генерации и платежи не имитируются', credits:'кредитов', noPlan:'Без подписки', guest:'Гость', profile:'Профиль', upgrade:'Больше возможностей', upgradeText:'Дай своим идеям больше пространства.', seePlans:'Посмотреть тарифы',
 prompt1:'Придумай идею для бренда', prompt2:'Создай атмосферное фото', prompt3:'Напиши сценарий ролика', prompt4:'Настрой AI-помощника',
 imageDesc:'Превращай идеи в изображения', videoDesc:'Воплощай истории в движении', voiceDesc:'Пусть твои слова зазвучат', faceDesc:'Редактирование с согласия человека', liveDesc:'Говори, спрашивай, вдохновляйся', botsDesc:'Помощники для твоих задач', chatDesc:'Думай и создавай вместе с AI',
 model:'Модель', format:'Формат', quality:'Качество', duration:'Длительность', language:'Язык ответа', choose:'Выбрать', needs:'Нужно подключение', planned:'Планируется', connected:'Настроено', unavailable:'Эта функция ещё не подключена. Кредиты не списаны.', offline:'Это автономный предпросмотр. Для подключения сервисов запусти проект по инструкции.',
 signin:'Войти', signup:'Создать аккаунт', signout:'Выйти', google:'Продолжить с Google', email:'Электронная почта', password:'Пароль', forgot:'Забыли пароль?', reset:'Восстановить пароль', backLogin:'Вернуться ко входу', existing:'Уже есть аккаунт?', noAccount:'Нет аккаунта?', accept:'Я принимаю условия и политику конфиденциальности', authTitle:'Рады тебя видеть', authSub:'Твоё пространство для больших идей.', or:'или по почте', authMissing:'Настрой Supabase и почтовый провайдер, чтобы включить вход.', sent:'Проверь почту: отправлена ссылка. Если её нет, проверь «Спам» и настройки отправителя.', resend:'Отправить повторно', confirmed:'Проверка ссылки', invalidLink:'Ссылка недействительна или истекла. Запроси новую.', savePassword:'Сохранить новый пароль', passwordSaved:'Пароль обновлён.',
 start:'Начать создавать', explore:'Открыть предпросмотр', features:'Возможности', pricing:'Тарифы', landing1:'Создавай.', landing2:'Общайся. Автоматизируй.', landingSub:'Фото, видео, голос и AI-помощники. Всё, что нужно твоим идеям, — в одном простом пространстве.', independent:'Независимая AI-платформа', allTools:'Много возможностей. Одно пространство.',
 plansTitle:'Выбери свой темп', plansSub:'Одна подписка. Общий баланс для всех инструментов.', month:'/ месяц', perMonth:'кредитов в месяц', characters:'AI-персонажей', resources:'подключений', concurrent:'задач одновременно', popular:'САМЫЙ ПОПУЛЯРНЫЙ', pickPlan:'Выбрать тариф', planNote:'Предварительные лимиты. Фото, видео и голос расходуют больше кредитов, чем короткий текст. Неиспользованные месячные кредиты не переносятся. Расходы на отдельные внешние API могут оплачиваться отдельно.', paymentMissing:'Оплата недоступна до настройки Stripe и webhook. Подписка не изменена.', balance:'Твой баланс', used:'Использовано за период', renewal:'Следующее обновление', portal:'Управление подпиской',
 botTitle:'Твоя команда AI', botSub:'Разные характеры. Одна большая идея.', createBot:'Создать бота', botName:'Имя помощника', role:'Роль и инструкции', tone:'Стиль общения', friendly:'Дружелюбный', business:'Деловой', playful:'Весёлый', serious:'Серьёзный', topic:'Тематика', daily:'Кредитов в день', save:'Сохранить', cancel:'Отмена', draft:'Черновик', botSafety:'Боты обозначаются как AI. Скрытая накрутка, фальшивые профили и спам не поддерживаются.', botSaved:'Черновик сохранён. Для запуска требуется интеграция.', localDraft:'Локальный черновик · хранится только в этом браузере', delete:'Удалить',
 connectTitle:'Твои сервисы, вместе', connectSub:'Подключай только аккаунты и сайты, которыми вправе управлять.', connect:'Как подключить', telegramDesc:'AI-помощник для твоей группы', webDesc:'Виджет на твоём сайте', socialDesc:'Черновики, расписание и ответы', steamDesc:'Возможности API требуют проверки', integrationNote:'Интеграции — следующий этап. Здесь не нужно вводить пароли или секретные токены.',
 emptyLibrary:'Здесь будут твои работы', librarySub:'Готовые изображения, видео и озвучки появятся здесь после подключения генераций.', emptyChat:'История сохраняется на сервере только при настроенном входе.', upload:'Загрузить фото', camera:'Камера', file:'Прикрепить файл', fileLimit:'Допустимы JPEG, PNG, WebP и TXT до 10 МБ.', attachmentNote:'Файл выбран локально. В этой версии отправка вложений в AI ещё не подключена.', micUnavailable:'Диктовка не поддерживается этим браузером. Используй Chrome через HTTPS.', micError:'Не удалось начать запись. Проверь разрешение на микрофон.', recording:'Слушаю… нажми, чтобы остановить', dictationNotice:'Диктовка использует службу распознавания браузера. Аудио может обрабатываться её провайдером.', send:'Отправить', close:'Закрыть', back:'Назад', home:'Главная', theme:'Оформление', light:'Светлое', interfaceLang:'Язык интерфейса', settingsSub:'Сделай пространство своим.', privacy:'Конфиденциальность', terms:'Условия', legal:'Шаблон для разработки, не опубликованная оферта. Перед запуском владелец должен добавить реквизиты, правила возвратов, политику хранения и удаления данных, основания обработки и контакты поддержки. Не вводи чувствительные данные в демонстрацию.', consentFace:'У меня есть права и согласие человека на редактирование.', cost:'Стоимость', fromCredit:'1 кредит · короткий текст', noCost:'Будет доступна после подключения модели', generating:'Генерация…', error:'Не удалось выполнить запрос. Попробуй позже.', notLogged:'Сначала войди в аккаунт.', noCredits:'Недостаточно кредитов. Проверь подписку.', noHistory:'Новых диалогов пока нет', faq:'Частые вопросы', faqQ:'Можно начать без настройки API?', faqA:'Да, можно изучить интерфейс. Реальная генерация, регистрация и оплата требуют подключения соответствующих сервисов.', stop:'Остановить', footer:'Сделано для больших идей.', accountSaved:'Настройки сохранены.', botLimit:'Достигнут лимит персонажей текущего тарифа.', confirmReset:'Если аккаунт существует, придёт письмо со ссылкой.',
},
en: {
 tagline:'Your ideas. AI power.', newChat:'New chat', workspace:'Workspace', chat:'AI chat', image:'Images', video:'Video', voice:'Voiceover', face:'Face Swap', live:'Talk to AI', bots:'My bots', integrations:'Connections', library:'Library', billing:'Plans & credits', settings:'Settings', tools:'TOOLS', manage:'MANAGE',
 welcome:'A little space for big ideas', headline:'What will we', today:'create today?', intro:'From your first “what if” to something wonderful.', placeholder:'Describe your idea…', hint:'Enter to send · Shift + Enter for a new line', aiNote:'AI can make mistakes. Check important information.', demo:'Preview', demoNote:'Interface demo · no simulated generations or payments', credits:'credits', noPlan:'No subscription', guest:'Guest', profile:'Profile', upgrade:'Room for more', upgradeText:'Give your ideas a little more space.', seePlans:'Explore plans',
 prompt1:'Find an idea for my brand', prompt2:'Create an atmospheric photo', prompt3:'Write a video script', prompt4:'Set up an AI assistant',
 imageDesc:'Turn your ideas into images', videoDesc:'Bring your stories to life', voiceDesc:'Give your words a voice', faceDesc:'Edit with the person’s consent', liveDesc:'Talk, ask, get inspired', botsDesc:'Assistants for your everyday', chatDesc:'Think and create with AI',
 model:'Model', format:'Format', quality:'Quality', duration:'Duration', language:'Response language', choose:'Choose', needs:'Setup required', planned:'Planned', connected:'Configured', unavailable:'This feature is not connected yet. No credits were charged.', offline:'This is an offline preview. Run the project to connect services.',
 signin:'Sign in', signup:'Create account', signout:'Sign out', google:'Continue with Google', email:'Email address', password:'Password', forgot:'Forgot password?', reset:'Reset password', backLogin:'Back to sign in', existing:'Already have an account?', noAccount:'New here?', accept:'I accept the terms and privacy policy', authTitle:'Welcome back', authSub:'Your space for big ideas.', or:'or with email', authMissing:'Configure Supabase and an email provider to enable sign in.', sent:'Check your inbox for a link. If missing, check spam and sender settings.', resend:'Resend email', confirmed:'Checking your link', invalidLink:'This link is invalid or expired. Request a new one.', savePassword:'Save new password', passwordSaved:'Password updated.',
 start:'Start creating', explore:'Open preview', features:'Features', pricing:'Pricing', landing1:'Create.', landing2:'Connect. Automate.', landingSub:'Images, video, voice and AI assistants. Everything your ideas need, in one simple space.', independent:'An independent AI platform', allTools:'Many possibilities. One space.',
 plansTitle:'Find your pace', plansSub:'One subscription. A shared balance for every tool.', month:'/ month', perMonth:'credits per month', characters:'AI characters', resources:'connections', concurrent:'concurrent tasks', popular:'MOST POPULAR', pickPlan:'Choose plan', planNote:'Provisional limits. Images, video and voice use more credits than short text. Unused monthly credits do not roll over. Some external API access may cost extra.', paymentMissing:'Payments require Stripe and webhook setup. Your subscription has not changed.', balance:'Your balance', used:'Used this period', renewal:'Next renewal', portal:'Manage subscription',
 botTitle:'Your AI team', botSub:'Different personalities. One big idea.', createBot:'Create a bot', botName:'Assistant name', role:'Role and instructions', tone:'Communication style', friendly:'Friendly', business:'Business', playful:'Playful', serious:'Serious', topic:'Topic', daily:'Credits per day', save:'Save', cancel:'Cancel', draft:'Draft', botSafety:'Bots are identified as AI. Hidden engagement farming, fake profiles and spam are not supported.', botSaved:'Draft saved. A connection is required to launch.', localDraft:'Local draft · stored in this browser only', delete:'Delete',
 connectTitle:'Your services, together', connectSub:'Connect only accounts and sites you are authorized to manage.', connect:'Setup details', telegramDesc:'An AI assistant for your group', webDesc:'A widget for your website', socialDesc:'Drafts, scheduling and replies', steamDesc:'API capabilities need verification', integrationNote:'Integrations are the next stage. Do not enter passwords or secret tokens here.',
 emptyLibrary:'Your creations will live here', librarySub:'Images, video and voiceovers will appear here once generation providers are connected.', emptyChat:'History is stored on the server only when sign-in is configured.', upload:'Upload photo', camera:'Camera', file:'Attach file', fileLimit:'JPEG, PNG, WebP and TXT files up to 10 MB are allowed.', attachmentNote:'File selected locally. Sending attachments to AI is not connected in this version.', micUnavailable:'Dictation is not supported here. Try Chrome over HTTPS.', micError:'Could not start recording. Check microphone permission.', recording:'Listening… tap to stop', dictationNotice:'Dictation uses your browser’s recognition service. Its provider may process your audio.', send:'Send', close:'Close', back:'Back', home:'Home', theme:'Appearance', light:'Light', interfaceLang:'Interface language', settingsSub:'Make this space your own.', privacy:'Privacy', terms:'Terms', legal:'Development template, not published legal terms. Before launch, the owner must add business details, refund rules, data retention and deletion policy, processing grounds, and support contacts. Do not enter sensitive data in this demo.', consentFace:'I have the rights and the person’s consent to edit.', cost:'Cost', fromCredit:'1 credit · short text', noCost:'Available after model setup', generating:'Generating…', error:'The request failed. Please try again later.', notLogged:'Please sign in first.', noCredits:'Not enough credits. Check your subscription.', noHistory:'No conversations yet', faq:'Questions, answered', faqQ:'Can I explore without API setup?', faqA:'Yes, you can explore the interface. Actual generation, sign-in and payments require the relevant services to be configured.', stop:'Stop', footer:'Made for big ideas.', accountSaved:'Preferences saved.', botLimit:'Your plan’s character limit has been reached.', confirmReset:'If the account exists, an email with a link will arrive.',
},
de: {
 tagline:'Deine Ideen. Die Kraft von AI.', newChat:'Neuer Chat', workspace:'Arbeitsbereich', chat:'AI-Chat', image:'Bilder', video:'Video', voice:'Sprachausgabe', face:'Face Swap', live:'Mit AI sprechen', bots:'Meine Bots', integrations:'Verbindungen', library:'Bibliothek', billing:'Tarife & Credits', settings:'Einstellungen', tools:'WERKZEUGE', manage:'VERWALTUNG',
 welcome:'Ein Ort für deine Ideen', headline:'Was erschaffen wir', today:'heute?', intro:'Vom ersten „Was wäre, wenn“ zu etwas Besonderem.', placeholder:'Beschreibe deine Idee…', hint:'Enter zum Senden · Shift + Enter für eine neue Zeile', aiNote:'AI kann Fehler machen. Prüfe wichtige Informationen.', demo:'Vorschau', demoNote:'Interface-Demo · keine simulierten Generierungen oder Zahlungen', credits:'Credits', noPlan:'Kein Abonnement', guest:'Gast', profile:'Profil', upgrade:'Mehr Möglichkeiten', upgradeText:'Gib deinen Ideen mehr Raum.', seePlans:'Tarife ansehen',
 prompt1:'Eine Idee für meine Marke', prompt2:'Ein stimmungsvolles Foto', prompt3:'Ein Videoskript schreiben', prompt4:'Einen AI-Assistenten einrichten',
 imageDesc:'Verwandle Ideen in Bilder', videoDesc:'Erwecke Geschichten zum Leben', voiceDesc:'Gib deinen Worten eine Stimme', faceDesc:'Bearbeitung mit Einwilligung', liveDesc:'Sprechen, fragen, inspirieren', botsDesc:'Assistenten für deine Aufgaben', chatDesc:'Mit AI denken und gestalten',
 model:'Modell', format:'Format', quality:'Qualität', duration:'Dauer', language:'Antwortsprache', choose:'Auswählen', needs:'Einrichtung nötig', planned:'Geplant', connected:'Konfiguriert', unavailable:'Diese Funktion ist noch nicht verbunden. Keine Credits abgebucht.', offline:'Dies ist eine Offline-Vorschau. Starte das Projekt, um Dienste zu verbinden.',
 signin:'Anmelden', signup:'Konto erstellen', signout:'Abmelden', google:'Weiter mit Google', email:'E-Mail-Adresse', password:'Passwort', forgot:'Passwort vergessen?', reset:'Passwort zurücksetzen', backLogin:'Zur Anmeldung', existing:'Schon ein Konto?', noAccount:'Noch kein Konto?', accept:'Ich akzeptiere die Bedingungen und Datenschutzhinweise', authTitle:'Willkommen zurück', authSub:'Dein Raum für große Ideen.', or:'oder mit E-Mail', authMissing:'Supabase und einen E-Mail-Anbieter einrichten, um die Anmeldung zu aktivieren.', sent:'Prüfe dein Postfach. Falls der Link fehlt, Spam und Absendereinstellungen prüfen.', resend:'Erneut senden', confirmed:'Link wird geprüft', invalidLink:'Dieser Link ist ungültig oder abgelaufen. Fordere einen neuen an.', savePassword:'Neues Passwort speichern', passwordSaved:'Passwort aktualisiert.',
 start:'Jetzt kreativ werden', explore:'Vorschau öffnen', features:'Funktionen', pricing:'Tarife', landing1:'Gestalten.', landing2:'Verbinden. Automatisieren.', landingSub:'Bilder, Video, Stimme und AI-Assistenten. Alles für deine Ideen an einem einfachen Ort.', independent:'Eine unabhängige AI-Plattform', allTools:'Viele Möglichkeiten. Ein Ort.',
 plansTitle:'Finde deinen Rhythmus', plansSub:'Ein Abonnement. Ein Guthaben für alle Werkzeuge.', month:'/ Monat', perMonth:'Credits pro Monat', characters:'AI-Charaktere', resources:'Verbindungen', concurrent:'gleichzeitige Aufgaben', popular:'AM BELIEBTESTEN', pickPlan:'Tarif wählen', planNote:'Vorläufige Limits. Bilder, Video und Stimme kosten mehr Credits als kurze Texte. Ungenutzte monatliche Credits verfallen. Externe APIs können zusätzlich kosten.', paymentMissing:'Zahlungen erfordern Stripe und Webhook-Einrichtung. Dein Abo wurde nicht geändert.', balance:'Dein Guthaben', used:'In diesem Zeitraum genutzt', renewal:'Nächste Erneuerung', portal:'Abonnement verwalten',
 botTitle:'Dein AI-Team', botSub:'Verschiedene Charaktere. Eine große Idee.', createBot:'Bot erstellen', botName:'Name des Assistenten', role:'Rolle und Anweisungen', tone:'Kommunikationsstil', friendly:'Freundlich', business:'Geschäftlich', playful:'Fröhlich', serious:'Ernst', topic:'Thema', daily:'Credits pro Tag', save:'Speichern', cancel:'Abbrechen', draft:'Entwurf', botSafety:'Bots werden als AI gekennzeichnet. Verdeckte Interaktionstäuschung, falsche Profile und Spam werden nicht unterstützt.', botSaved:'Entwurf gespeichert. Zum Starten ist eine Verbindung nötig.', localDraft:'Lokaler Entwurf · nur in diesem Browser', delete:'Löschen',
 connectTitle:'Deine Dienste, zusammen', connectSub:'Verbinde nur Konten und Websites, die du verwalten darfst.', connect:'Einrichtung', telegramDesc:'AI-Assistent für deine Gruppe', webDesc:'Widget für deine Website', socialDesc:'Entwürfe, Planung und Antworten', steamDesc:'API-Funktionen müssen geprüft werden', integrationNote:'Integrationen folgen in der nächsten Phase. Hier keine Passwörter oder geheimen Tokens eingeben.',
 emptyLibrary:'Hier wohnen deine Werke', librarySub:'Bilder, Videos und Sprachaufnahmen erscheinen nach der Anbindung von Anbietern.', emptyChat:'Der Verlauf wird nur bei eingerichtetem Login auf dem Server gespeichert.', upload:'Foto hochladen', camera:'Kamera', file:'Datei anhängen', fileLimit:'JPEG, PNG, WebP und TXT bis 10 MB sind erlaubt.', attachmentNote:'Datei lokal ausgewählt. AI-Anhänge sind in dieser Version noch nicht angebunden.', micUnavailable:'Diktieren wird hier nicht unterstützt. Versuche Chrome über HTTPS.', micError:'Aufnahme nicht möglich. Mikrofonberechtigung prüfen.', recording:'Ich höre zu… zum Stoppen tippen', dictationNotice:'Diktieren nutzt den Erkennungsdienst deines Browsers. Dessen Anbieter kann Audio verarbeiten.', send:'Senden', close:'Schließen', back:'Zurück', home:'Startseite', theme:'Darstellung', light:'Hell', interfaceLang:'Oberflächensprache', settingsSub:'Mach diesen Raum zu deinem.', privacy:'Datenschutz', terms:'Bedingungen', legal:'Entwicklungsvorlage, keine veröffentlichten Vertragsbedingungen. Vor dem Start müssen Firmendaten, Erstattungsregeln, Datenspeicherung und -löschung, Rechtsgrundlagen und Supportkontakt ergänzt werden. Keine sensiblen Daten in dieser Demo eingeben.', consentFace:'Ich habe die Rechte und die Einwilligung zur Bearbeitung.', cost:'Kosten', fromCredit:'1 Credit · kurzer Text', noCost:'Nach Modelleinrichtung verfügbar', generating:'Wird generiert…', error:'Anfrage fehlgeschlagen. Bitte später erneut versuchen.', notLogged:'Bitte zuerst anmelden.', noCredits:'Nicht genug Credits. Prüfe dein Abonnement.', noHistory:'Noch keine Chats', faq:'Häufige Fragen', faqQ:'Kann ich ohne API-Einrichtung starten?', faqA:'Ja, die Oberfläche ist frei erkundbar. Echte Generierung, Anmeldung und Zahlungen benötigen eingerichtete Dienste.', stop:'Stoppen', footer:'Für große Ideen gemacht.', accountSaved:'Einstellungen gespeichert.', botLimit:'Das Charakterlimit deines Tarifs ist erreicht.', confirmReset:'Falls das Konto existiert, kommt eine E-Mail mit einem Link.',
}
};
export type Text = typeof copy.en;
