'use client';
import {useEffect,useRef,useState} from 'react';
import {Plus, ArrowUp, ArrowUpRight, ArrowRight, ChevronDown, Menu, X, Mic, Image as ImageIcon, Clapperboard, AudioLines, MessagesSquare, Bot, Link as LinkIcon, LayoutGrid, Settings, Sparkles, Zap, Check, Globe2, LogOut, Camera, Paperclip, FileText, ShieldCheck, CircleHelp, Clock, LoaderCircle, Trash2, WandSparkles} from 'lucide-react';
import Gorilla from './Gorilla';
import {copy, type Lang} from '../lib/i18n';
import {api,blankConfig,getAuth,type Config} from '../lib/browser';
import {AuthPanel,Plans,Bots,Connections,Preferences} from './Panels';
export type Mode='chat'|'image'|'video'|'voice'|'face'|'live';
export type Account={email:string;plan:string;credits:number;used:number;renewal:string|null;language:string;id:string};
export const modes:Mode[]=['chat','image','video','voice','face','live'];
export const icons={chat:MessagesSquare,image:ImageIcon,video:Clapperboard,voice:AudioLines,face:WandSparkles,live:Mic};
const modelLists:Record<Mode,string[]>={chat:['OpenAI'],image:['GPT Image · OpenAI','Nano Banana · Google'],video:['OpenAI','Google','Kling','MiniMax','Seedance','Grok / xAI','HappyHorse'],voice:['ElevenLabs'],face:['Face Swap'],live:['OpenAI Realtime']};
export default function App({preview=false}:{preview?:boolean}){
 const [lang,setLang]=useState<Lang>('ru');const t=copy[lang];
 const [view,setView]=useState(preview?'workspace':'landing');const [mode,setMode]=useState<Mode>('chat');
 const [config,setConfig]=useState<Config>({...blankConfig,offline:preview});const [account,setAccount]=useState<Account|null>(null);
 const [sidebar,setSidebar]=useState(false);const [plus,setPlus]=useState(false);const [profile,setProfile]=useState(false);const [authMode,setAuthMode]=useState('signin');
 const [toast,setToast]=useState('');const [text,setText]=useState('');const [model,setModel]=useState('OpenAI');const [busy,setBusy]=useState(false);const [attachment,setAttachment]=useState<File|null>(null);
 const [consent,setConsent]=useState(false);const [recording,setRecording]=useState(false);const recognition=useRef<any>(null);
 const [messages,setMessages]=useState<{role:string;content:string}[]>([]);const [conversations,setConversations]=useState<{id:string;title:string}[]>([]);const [conversation,setConversation]=useState<string|null>(null);
 const [legal,setLegal]=useState(false); const fileRef=useRef<HTMLInputElement>(null);const cameraRef=useRef<HTMLInputElement>(null);const inputRef=useRef<HTMLTextAreaElement>(null);const endRef=useRef<HTMLDivElement>(null);const toastTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 function notify(s:string){setToast(s);if(toastTimer.current)clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),6000);}
 function fail(e:unknown){const s=e instanceof Error?e.message:'';notify(s==='OFFLINE'?t.offline:s==='UNAUTHORIZED'?t.notLogged:s==='NO_CREDITS'?t.noCredits:s==='NOT_CONFIGURED'?t.unavailable:s==='BOT_LIMIT'?t.botLimit:t.error);}
 function navigate(v:string){setView(v);setSidebar(false);setPlus(false);setProfile(false);history.replaceState(null,'',preview?'#'+v:'/#'+v);}
 function selectMode(m:Mode){setMode(m);setModel(m==='chat'?config.model:modelLists[m][0]);navigate('workspace');setMessages([]);setConversation(null);setAttachment(null);}
 async function refresh(c=config){if(!getAuth(c))return;try{const r=await api('account',c);setAccount(r.account);setConversations(r.conversations||[]);if(r.account.language in copy)setLang(r.account.language);}catch{setAccount(null);}}
 useEffect(()=>{const saved=localStorage.getItem('animal-language');if(saved&&saved in copy)setLang(saved as Lang);if(preview)return;
 fetch('/api/config').then(r=>r.json()).then(async(c:Config)=>{setConfig(c);setModel(c.model);const auth=getAuth(c);if(!auth)return;const params=new URLSearchParams(location.search);const hash=new URLSearchParams(location.hash.slice(1));
 if(params.has('code')){const {error}=await auth.auth.exchangeCodeForSession(params.get('code')!);history.replaceState(null,'','/');if(error){setView('auth');setToast(copy.ru.invalidLink);}else if(params.get('flow')==='recovery'){setAuthMode('update');setView('auth');}else setView('workspace');}
 else if(params.has('error')||hash.has('error')){setToast(copy.ru.invalidLink);setView('auth');}
 const {data}=await auth.auth.getSession();if(data.session){await refresh(c);if(!params.has('code'))setView('workspace');}
 }).catch(()=>{});
 const vv=window.visualViewport;function resize(){document.documentElement.style.setProperty('--app-height',`${vv?.height||window.innerHeight}px`);}resize();vv?.addEventListener('resize',resize);return()=>{vv?.removeEventListener('resize',resize);recognition.current?.stop();};
 },[]);
 useEffect(()=>{if(!config.supabaseUrl)return;const auth=getAuth(config)!;const {data}=auth.auth.onAuthStateChange((event)=>{if(event==='SIGNED_OUT'){setAccount(null);setConversations([]);setMessages([]);setView('landing');}else if(event==='SIGNED_IN'||event==='TOKEN_REFRESHED')setTimeout(()=>refresh(config),0);});return()=>data.subscription.unsubscribe();},[config]);
 useEffect(()=>{document.documentElement.lang=lang;localStorage.setItem('animal-language',lang);},[lang]);
 useEffect(()=>{endRef.current?.scrollIntoView({behavior:'smooth',block:'nearest'});},[messages,busy]);
 useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape'){setPlus(false);setProfile(false);setSidebar(false);setLegal(false);}};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[]);
 function changeLang(l:Lang){setLang(l);if(account)api('account',config,{language:l},'PATCH').catch(fail);}
 async function send(){if(!text.trim()||busy)return;if(attachment)return notify(t.attachmentNote);if(mode!=='chat'||!config.chat)return notify(config.offline?t.offline:t.unavailable);if(!account)return notify(t.notLogged);
 const prompt=text.trim();setBusy(true);setText('');setMessages(m=>[...m,{role:'user',content:prompt}]);try{const r=await api('chat',config,{prompt,conversationId:conversation,language:lang,requestId:crypto.randomUUID()});setConversation(r.conversationId);setMessages(m=>[...m,{role:'assistant',content:r.text}]);await refresh();}catch(e){setText(prompt);setMessages(m=>m.slice(0,-1));fail(e);}finally{setBusy(false);}}
 async function loadChat(id:string){try{const r=await api('chat?id='+encodeURIComponent(id),config);setMessages(r.messages);setConversation(id);setMode('chat');setModel(config.model);navigate('workspace');}catch(e){fail(e);}}
 function dictate(){if(recording){recognition.current?.stop();return;}const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR)return notify(t.micUnavailable);if(!window.confirm(t.dictationNotice))return;const r=new SR();r.lang={ru:'ru-RU',en:'en-US',de:'de-DE'}[lang];r.interimResults=false;r.onresult=(e:any)=>setText(v=>v+(v?' ':'')+e.results[0][0].transcript);r.onerror=()=>{notify(t.micError);setRecording(false);};r.onend=()=>setRecording(false);recognition.current=r;try{r.start();setRecording(true);}catch{notify(t.micError);}}
 function chooseFile(file?:File){if(!file)return;if(file.size>10*1024*1024||!['image/jpeg','image/png','image/webp','text/plain'].includes(file.type))return notify(t.fileLimit);setAttachment(file);setPlus(false);notify(t.attachmentNote);}
 const languagePicker=<label className="language-picker"><Globe2 size={15}/><select aria-label={t.interfaceLang} value={lang} onChange={e=>changeLang(e.target.value as Lang)}><option value="ru">RU</option><option value="en">EN</option><option value="de">DE</option></select></label>;
 const brand=<button className="brand" onClick={()=>navigate('landing')}><Gorilla/><span>ANIMAL<span className="brand-ai"> AI</span></span></button>;
 const auth=(m:string)=>{setAuthMode(m);navigate('auth');};
 const toolsPanel=<div className="tool-popup" role="dialog" aria-label={t.tools}><div className="sheet-grip"/><div className="popup-head"><span>{t.tools}</span><button className="icon-button" aria-label={t.close} onClick={()=>setPlus(false)}><X size={18}/></button></div><div className="upload-row"><button onClick={()=>fileRef.current?.click()}><ImageIcon/>{t.upload}</button><button onClick={()=>cameraRef.current?.click()}><Camera/>{t.camera}</button><button onClick={()=>fileRef.current?.click()}><Paperclip/>{t.file}</button></div>{modes.map(m=>{const Icon=icons[m];return <button key={m} className={'tool-option '+(mode===m?'selected':'')} onClick={()=>selectMode(m)}><span className={'tool-icon '+m}><Icon size={21}/></span><span><strong>{t[m]}</strong><small>{t[(m+'Desc') as keyof typeof t]}</small></span>{mode===m?<Check size={17}/>:<ArrowUpRight size={16}/>}</button>;})}<button className="tool-option" onClick={()=>navigate('bots')}><span className="tool-icon bots"><Bot size={21}/></span><span><strong>{t.bots}</strong><small>{t.botsDesc}</small></span><ArrowUpRight size={16}/></button></div>;
 return <div className={'app '+(view==='landing'?'landing-app':'')}>
 {view==='landing'?<><header className="landing-header">{brand}<nav><button onClick={()=>document.getElementById('features')?.scrollIntoView({behavior:'smooth'})}>{t.features}</button><button onClick={()=>navigate('billing')}>{t.pricing}</button></nav><div className="header-right">{languagePicker}<button className="text-button" onClick={()=>auth('signin')}>{t.signin}</button><button className="primary small" onClick={()=>auth('signup')}>{t.signup}</button></div></header>
 <main className="landing-main"><section className="landing-hero"><div className="hero-ambient"/><div className="hero-orbit"><Gorilla/></div><div className="eyebrow"><span className="status-dot"/>{t.independent}</div><h1>{t.landing1}<br/><span>{t.landing2}</span></h1><p>{t.landingSub}</p><div className="hero-actions"><button className="primary" onClick={()=>auth('signup')}>{t.start}<ArrowRight size={17}/></button><button className="secondary" onClick={()=>navigate('workspace')}>{t.explore}<ArrowUpRight size={17}/></button></div><div className="provider-line">OpenAI <span>·</span> Google <span>·</span> Claude <span>·</span> ElevenLabs <small>{t.planned}</small></div></section><section id="features" className="feature-section"><p className="eyebrow">ANIMAL AI / STUDIO</p><h2>{t.allTools}</h2><div className="feature-grid">{(['image','video','voice','chat'] as Mode[]).map(m=>{const Icon=icons[m];return <button className={'feature-card '+m} key={m} onClick={()=>selectMode(m)}><Icon size={26}/><ArrowUpRight className="feature-arrow" size={20}/><h3>{t[m]}</h3><p>{t[(m+'Desc') as keyof typeof t]}</p></button>;})}</div></section><Plans t={t} lang={lang} config={config} account={account} notify={notify} fail={fail}/><section className="faq"><h2>{t.faq}</h2><details><summary>{t.faqQ}<Plus size={18}/></summary><p>{t.faqA}</p></details></section></main><footer>{brand}<span>{t.footer}</span><button onClick={()=>setLegal(true)}>{t.privacy}</button><button onClick={()=>setLegal(true)}>{t.terms}</button></footer></>:
 <>{sidebar&&<button className="sidebar-overlay" aria-label={t.close} onClick={()=>setSidebar(false)}/>}<aside className={'sidebar '+(sidebar?'open':'')}>{brand}<button className="new-chat" onClick={()=>selectMode('chat')}><Plus size={19}/>{t.newChat}<span>↗</span></button><div className="nav-caption">{t.tools}</div><nav>{modes.filter(m=>m!=='face').map(m=>{const Icon=icons[m];return <button className={view==='workspace'&&mode===m?'active':''} onClick={()=>selectMode(m)} key={m}><Icon size={18}/>{t[m]}{m==='live'&&<span className="new-dot"/>}</button>;})}</nav><div className="nav-caption">{t.manage}</div><nav>{[['bots',Bot],['integrations',LinkIcon],['library',LayoutGrid]] .map(([v,I])=>{const Icon=I as typeof Bot;return <button key={v as string} className={view===v?'active':''} onClick={()=>navigate(v as string)}><Icon size={18}/>{t[v as 'bots']}</button>;})}</nav><div className="recent-chats">{conversations.slice(0,4).map(c=><button key={c.id} onClick={()=>loadChat(c.id)}><MessagesSquare size={13}/><span>{c.title}</span></button>)}</div><div className="sidebar-bottom"><div className="upgrade-box"><div className="upgrade-symbol"><Sparkles size={17}/></div><strong>{t.upgrade}</strong><p>{t.upgradeText}</p><button onClick={()=>navigate('billing')}>{t.seePlans}<ArrowUpRight size={15}/></button></div><button className="settings-nav" onClick={()=>navigate('settings')}><Settings size={18}/>{t.settings}</button><span className="version">ANIMAL AI <span>EARLY ACCESS</span></span></div></aside>
 <div className="main-shell"><header className="app-header"><div className="header-left"><button className="icon-button mobile-menu" onClick={()=>setSidebar(true)} aria-label={t.tools}><Menu size={22}/></button><span className="breadcrumb">{t.workspace}<span>/</span></span><strong>{view==='workspace'?t[mode]:view==='auth'?t.signin:t[view as 'bots']}</strong>{view==='workspace'&&<span className="subtle-tag">BETA</span>}</div><div className="header-right">{languagePicker}<button className="credit-pill" onClick={()=>navigate('billing')}><Zap size={14}/><span>{account?account.credits.toLocaleString(lang):'0'}</span><small>{t.credits}</small></button><div className="profile-wrap"><button className="avatar" aria-label={t.profile} onClick={()=>setProfile(!profile)}>{account?account.email[0].toUpperCase():<Gorilla/>}</button>{profile&&<div className="profile-menu"><strong>{account?.email||t.guest}</strong><small>{account?.plan==='none'||!account?t.noPlan:account.plan.toUpperCase()}</small><div className="profile-balance"><Zap size={16}/>{account?.credits||0} {t.credits}</div><button onClick={()=>navigate('billing')}>{t.billing}<ArrowUpRight size={15}/></button><button onClick={()=>navigate('settings')}>{t.settings}</button>{account?<button onClick={async()=>{await getAuth(config)?.auth.signOut();setProfile(false);}}><LogOut size={16}/>{t.signout}</button>:<button onClick={()=>auth('signin')}>{t.signin}<ArrowRight size={16}/></button>}</div>}</div></div></header>
 {view==='workspace'?<main className="workspace"><div className="workspace-scroll">{messages.length===0?<section className="welcome"><div className="welcome-emblem"><Gorilla/><span className="emblem-spark"><Sparkles size={13}/></span></div><p className="eyebrow">{t.welcome}</p><h1>{t.headline}<br/><span>{t.today}</span></h1><p className="welcome-sub">{t.intro}</p><div className="suggestions">{[1,2,3,4].map((n)=>{const Icon=[Sparkles,ImageIcon,Clapperboard,Bot][n-1];return <button key={n} onClick={()=>{if(n===4)navigate('bots');else{selectMode(n===2?'image':'chat');setText(t[('prompt'+n) as keyof typeof t]);inputRef.current?.focus();}}}><Icon size={16}/>{t[('prompt'+n) as keyof typeof t]}<ArrowUpRight size={13}/></button>;})}</div></section>:<div className="messages">{messages.map((m,i)=><div key={i} className={'message '+m.role}>{m.role==='assistant'&&<Gorilla/>}<div>{m.content}</div></div>)}{busy&&<div className="thinking"><LoaderCircle size={16} className="spin"/>{t.generating}</div>}<div ref={endRef}/></div>}</div>
 <div className="composer-area"><div className="mode-rail"><div className="mode-switch">{(['chat','image','video','voice'] as Mode[]).map(m=>{const Icon=icons[m];return <button key={m} className={mode===m?'selected':''} onClick={()=>selectMode(m)}><Icon size={15}/>{t[m]}</button>;})}</div><span className="private-note"><ShieldCheck size={13}/>ANIMAL AI</span></div>
 {mode!=='chat'&&<div className="generation-settings"><span className="status-chip"><span/>{t.needs}</span>{mode==='image'||mode==='video'?<label>{t.format}<select><option>1:1</option><option>16:9</option><option>9:16</option></select></label>:null}{mode==='video'&&<label>{t.duration}<select><option>5 s</option><option>10 s</option></select></label>}{mode==='image'&&<label>{t.quality}<select><option>Standard</option><option>HD</option></select></label>}{mode==='voice'&&<label>{t.language}<select><option>Русский</option><option>English</option><option>Deutsch</option></select></label>}{mode==='face'&&<label className="checkbox"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>{t.consentFace}</label>}</div>}
 <div className={'composer '+(recording?'recording':'')}>{plus&&toolsPanel}{attachment&&<div className="attachment"><Paperclip size={13}/>{attachment.name}<button aria-label={t.delete} onClick={()=>setAttachment(null)}><X size={14}/></button></div>}<textarea ref={inputRef} aria-label={t.placeholder} placeholder={recording?t.recording:t.placeholder} value={text} maxLength={6000} rows={2} onChange={e=>{setText(e.target.value);e.target.style.height='auto';e.target.style.height=Math.min(e.target.scrollHeight,170)+'px';}} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send();}}}/><div className="composer-toolbar"><div className="toolbar-left"><button className={'icon-button plus-button '+(plus?'on':'')} onClick={()=>setPlus(!plus)} aria-expanded={plus} aria-label={t.tools}>{plus?<X size={22}/>:<Plus size={24}/>}</button><div className="toolbar-divider"/><label className="model-select"><span className="model-orb"/><select aria-label={t.model} value={model} onChange={e=>setModel(e.target.value)}>{(mode==='chat'?[config.model]:modelLists[mode]).map(m=><option key={m}>{m}</option>)}</select><ChevronDown size={13}/></label></div><div className="toolbar-right"><span className="cost-label">{mode==='chat'&&config.chat?t.fromCredit:t.needs}</span><button className={'icon-button mic '+(recording?'on':'')} aria-label={recording?t.stop:t.live} onClick={dictate}><Mic size={20}/></button><button className="send-button" aria-label={t.send} disabled={!text.trim()||busy||(mode==='face'&&!consent)} onClick={send}>{busy?<LoaderCircle className="spin" size={20}/>:<ArrowUp size={21}/>}</button></div></div></div><div className="composer-footer"><span>{t.aiNote}</span><span>{t.hint}</span></div></div></main>:
 view==='auth'?<AuthPanel config={config} t={t} lang={lang} fail={fail} authMode={authMode} setAuthMode={setAuthMode} notify={notify} onSuccess={()=>{refresh();navigate('workspace');}} legal={()=>setLegal(true)}/>:<main className="page-content">
 {view==='billing'&&<Plans t={t} lang={lang} config={config} account={account} notify={notify} fail={fail}/>}
 {view==='bots'&&<Bots t={t} lang={lang} config={config} account={account} notify={notify} fail={fail}/>}
 {view==='integrations'&&<Connections t={t} lang={lang} config={config} account={account} notify={notify} fail={fail}/>}
 {view==='library'&&<div className="empty-state"><div className="empty-icon"><LayoutGrid size={32}/></div><h1>{t.emptyLibrary}</h1><p>{t.librarySub}</p><button className="primary" onClick={()=>selectMode('image')}>{t.image}<ArrowRight size={16}/></button></div>}
 {view==='settings'&&<Preferences t={t} lang={lang} config={config} account={account} notify={notify} fail={fail} setLang={changeLang}/>}
 </main>}
 <div className="demo-bar"><span className="status-dot"/>{config.offline||!config.supabaseUrl?t.demoNote:'ANIMAL AI · EARLY ACCESS'}<button onClick={()=>navigate('landing')}>{t.home}<ArrowUpRight size={11}/></button></div></div></>}
 <input type="file" hidden ref={fileRef} accept="image/jpeg,image/png,image/webp,text/plain" onChange={e=>chooseFile(e.target.files?.[0])}/><input type="file" hidden ref={cameraRef} accept="image/*" capture="environment" onChange={e=>chooseFile(e.target.files?.[0])}/>
 {toast&&<div className="toast" role="status"><CircleHelp size={19}/><span>{toast}</span><button aria-label={t.close} onClick={()=>setToast('')}><X size={17}/></button></div>}
 {legal&&<div className="modal-backdrop" onClick={()=>setLegal(false)}><section className="modal legal-modal" role="dialog" aria-modal="true" aria-label={t.terms} onClick={e=>e.stopPropagation()}><button autoFocus className="icon-button modal-close" aria-label={t.close} onClick={()=>setLegal(false)}><X/></button><ShieldCheck size={28}/><h2>{t.terms} / {t.privacy}</h2><p>{t.legal}</p><button className="secondary" onClick={()=>setLegal(false)}>{t.close}</button></section></div>}
 </div>;
}
