'use client';
import {useEffect,useState} from 'react';
import {Check,ArrowRight,Bot,Link,Plus,Trash2} from 'lucide-react';
import {api,getAuth,type Config} from '../lib/browser';
import type {Account} from './App';
import type {Lang} from '../lib/i18n';
type Props={t:any;lang:Lang;config:Config;account?:Account|null;notify:(s:string)=>void;fail:(e:unknown)=>void};
export function AuthPanel({t,config,notify,mode,setMode,onDone,fail}:Props&{mode?:string;setMode?:(s:string)=>void;authMode?:string;setAuthMode?:(s:string)=>void;onDone?:()=>void;onSuccess?:()=>void;legal?:()=>void}){
 const current=mode||arguments[0]?.authMode||'signin'; const change= setMode||arguments[0]?.setAuthMode || (()=>{}); const done=onDone||arguments[0]?.onSuccess||(()=>{});
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[cooldown,setCooldown]=useState(0);
 useEffect(()=>{if(!cooldown)return;const timer=setTimeout(()=>setCooldown(c=>c-1),1000);return()=>clearTimeout(timer)},[cooldown]);
 async function submit(e:React.FormEvent){e.preventDefault();const a=getAuth(config);if(!a)return notify(t.authUnavailable);setBusy(true);try{let r:any;
 if(current==='signup')r=await a.auth.signUp({email,password,options:{emailRedirectTo:location.origin}});
 else if(current==='reset')r=await a.auth.resetPasswordForEmail(email,{redirectTo:location.origin+'/?flow=recovery'});
 else if(current==='update')r=await a.auth.updateUser({password});
 else if(current==='verify'){r=await a.auth.resend({type:'signup',email,options:{emailRedirectTo:location.origin}});setCooldown(60)}
 else r=await a.auth.signInWithPassword({email,password});
 if(r.error)throw r.error;
 if(current==='signup'||current==='verify'){change('verify');setCooldown(60);notify(t.verifySent)}else if(current==='reset')notify(t.resetSent);else done();
 }catch{notify(t.authError)}finally{setBusy(false)}}
 async function google(){const a=getAuth(config);if(!a)return notify(t.authUnavailable);const {error}=await a.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin}});if(error)fail?.(error)}
 return <main className="auth-page"><form className="auth-card" onSubmit={submit}><div className="eyebrow">ANIMAL AI</div><h1>{current==='signup'?t.signup:current==='reset'?t.resetTitle:current==='verify'?t.verifyTitle:current==='update'?t.newPassword:t.authTitle}</h1><p>{current==='verify'?t.verifyText:t.authSub}</p><div className="auth-tabs"><button type="button" className={current==='signin'?'active':''} onClick={()=>change('signin')}>{t.signin}</button><button type="button" className={current==='signup'?'active':''} onClick={()=>change('signup')}>{t.signup}</button></div><button type="button" className="secondary full" onClick={google}>G · {t.google}</button><div className="divider">{t.or}</div>{current!=='update'&&<label>{t.email}<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></label>}{!['reset','verify'].includes(current)&&<label>{t.password}<input type="password" minLength={8} required value={password} onChange={e=>setPassword(e.target.value)} autoComplete={current==='signin'?'current-password':'new-password'}/></label>}{current==='signup'&&<label className="check-label"><input required type="checkbox"/>{t.accept}</label>}<button className="primary full" disabled={busy||(current==='verify'&&cooldown>0)}>{busy?t.sending:current==='verify'?`${t.resend} ${cooldown||''}`:current==='reset'?t.sendReset:current==='signup'?t.signup:current==='update'?t.save:t.signin}<ArrowRight size={17}/></button><button type="button" className="text-button" onClick={()=>change(current==='verify'?'signup':'reset')}>{current==='verify'?t.editEmail:t.forgot}</button>{!config.supabaseUrl&&<p className="inline-notice">{t.authUnavailable}</p>}</form></main>
}
export function Plans({t,lang,config,account,notify,fail}:Props){async function checkout(plan:string){if(!account)return notify(t.notLogged);try{const r=await api('billing',config,{plan});location.assign(r.url)}catch(e){fail(e)}}return <section className="plans-section"><p className="eyebrow">ANIMAL AI / MEMBERSHIP</p><h1>{t.plansTitle}</h1><p className="section-sub">{t.plansSub}</p><div className="plans-grid">{[['Basic',10,1000,3,1,1],['Pro',30,3500,15,5,2],['Max',90,11000,50,15,4]].map(([name,price,credits,bots,resources,jobs],i)=><article className={'plan-card '+(i===1?'featured':'')} key={name}>{i===1&&<span className="plan-badge">{t.popular}</span>}<h2>{name}</h2><div className="price">${price}<small>{t.month}</small></div><p>{Number(credits).toLocaleString(lang)} {t.creditsMonth}</p><ul>{[`${bots} ${t.botSlots}`,`${resources} ${t.resources}`,`${jobs} ${t.concurrent}`,t.allModes].map((x,j)=><li key={j}><Check size={16}/>{x}</li>)}</ul><button className={i===1?'primary full':'secondary full'} onClick={()=>checkout(String(name).toLowerCase())}>{t.choosePlan}<ArrowRight size={16}/></button></article>)}</div><p className="plans-note">{t.creditPolicy}</p><p className="plans-note">{t.economics}</p>{!config.checkout&&<div className="inline-notice">{t.checkoutOff}</div>}</section>}
export function Bots({t,config,account,notify,fail}:Props){const [items,setItems]=useState<any[]>([]),[open,setOpen]=useState(false),[name,setName]=useState(''),[style,setStyle]=useState(t.friendly),[topic,setTopic]=useState(''),[instruction,setInstruction]=useState(''),[language,setLanguage]=useState('ru'),[budget,setBudget]=useState(20);useEffect(()=>{if(account)api('bots',config).then(r=>setItems(r.bots)).catch(fail)},[account?.id]);async function save(e:React.FormEvent){e.preventDefault();try{const r=await api('bots',config,{name,style,topic,instruction,language,budget});setItems([...items,r.bot]);setOpen(false);notify(t.botSaved)}catch(e){fail(e)}}return <main className="content-page"><div className="page-heading"><div><p className="eyebrow">AI AGENTS</p><h1>{t.bots}</h1><p>{t.botSubtitle}</p></div><button className="primary" onClick={()=>setOpen(!open)}><Plus size={18}/>{t.createBot}</button></div>{open&&<form className="form-panel" onSubmit={save}><label>{t.botName}<input required maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label><label>{t.style}<select value={style} onChange={e=>setStyle(e.target.value)}>{[t.friendly,t.business,t.playful,t.serious,t.custom].map(x=><option key={x}>{x}</option>)}</select></label><label>{t.topic}<input value={topic} onChange={e=>setTopic(e.target.value)}/></label><label>{t.instructions}<textarea required value={instruction} onChange={e=>setInstruction(e.target.value)}/></label><label>{t.replyLanguage}<select value={language} onChange={e=>setLanguage(e.target.value)}><option value="ru">Русский</option><option value="en">English</option><option value="de">Deutsch</option></select></label><label>{t.dailyBudget}<input type="number" min="1" max="1000" value={budget} onChange={e=>setBudget(+e.target.value)}/></label><p className="inline-notice">{t.botDisclosure}</p><button className="primary">{t.save}</button></form>}{items.length===0?<div className="empty-state"><Bot size={42}/><h2>{t.emptyBots}</h2><p>{t.emptyBotsSub}</p></div>:<div className="feature-grid">{items.map(b=><article className="feature-card" key={b.id}><Bot/><h3>{b.name}</h3><p>{b.style} · {b.language}</p><span className="status-chip muted">{t.disconnected}</span><button className="icon-button" aria-label={t.deleteBot} onClick={async()=>{try{await api('bots',config,{id:b.id},'DELETE');setItems(items.filter(x=>x.id!==b.id))}catch(e){fail(e)}}}><Trash2 size={16}/></button></article>)}</div>}</main>}
export function Connections({t,notify,config,account,fail}:Props){return <main className="content-page"><p className="eyebrow">CONNECTED WORKSPACE</p><h1>{t.connectionsTitle}</h1><p className="section-sub">{t.connectionsSub}</p><div className="connections-grid">{[['Telegram',t.telegramDesc],['Website',t.websiteDesc],['X / Twitter',t.socialDesc],['Threads',t.socialDesc],['Reddit',t.socialDesc],['Steam',t.steamDesc]].map(([name,desc])=><article className="connection-card" key={name}><div className="connection-logo"><Link size={24}/></div><h2>{name}</h2><p>{desc}</p><span className="status-chip muted">{name==='Steam'?t.planned:t.needsSetup}</span><button className="secondary full" onClick={()=>notify(name==='Steam'?t.steamDesc:t.notImplemented)}>{t.connect}<ArrowRight size={15}/></button></article>)}</div><div className="inline-notice">{t.integrationNote}</div></main>}
export function Preferences({t,lang,config,account,notify,fail,setLang}:Props&{setLang:(l:Lang)=>void}){return <main className="content-page"><h1>{t.settings}</h1><section className="form-panel"><h2>{t.profile}</h2><p>{account?.email||t.guest}</p><label>{t.interfaceLang}<select value={lang} onChange={e=>setLang(e.target.value as Lang)}><option value="ru">Русский</option><option value="en">English</option><option value="de">Deutsch</option></select></label><p>{t.dataNote}</p><button className="secondary" onClick={async()=>{try{const r=await api('export',config);const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(r,null,2)],{type:'application/json'}));a.download='animal-data.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}catch(e){fail(e)}}}>{t.exportData}</button><button className="text-button danger" onClick={async()=>{if(!confirm(t.deleteConfirm))return;try{await api('account',config,{},'DELETE');await getAuth(config)?.auth.signOut();notify(t.deleted)}catch(e){fail(e)}}}>{t.deleteAccount}</button></section></main>}
